export const data = [
  {
    alias: "ramranch",
    major: "Computer Science",
    hobbies:
      "My main hobbies include art (drawing) and game development, which I expect did in some way contribute to my choice of track (computer graphics). I am quite shy (social anxiety tends to do that), so for me the entire pandemic period was in some ways a good change.",
    statistics: 2,
    programming: 5,
    ux: 4,
  },
  {
    alias: "Caterpillar Fungus",
    major: "Media Technology",
    hobbies:
      "I am putting myself in an uncomfortable position in the two years at KTH so that I am forced to learn. I am a noob at programming and want to take it to another level by the time I graduate in 2025 so that I can build a viable product by the end of graduation.  My hobbies include cycling and playing football. I don't travel often and play computer games as I would like to.",
    statistics: 2,
    programming: 4,
    ux: 3,
  },
  {
    alias: "tjsol",
    major: "Human-Computer Interaction",
    hobbies: "Web Development",
    statistics: 3,
    programming: 7,
    ux: 6,
  },
  {
    alias: "Rookie9",
    major: "Computer Science",
    hobbies: "",
    statistics: 5,
    programming: 5,
    ux: 5,
  },
  {
    alias: "matcha",
    major: "Chemical Engineering + AI",
    hobbies:
      "Hello! I'm interested in learning how to incorporate AI into chemical engineering (hence my majors) like AI synthesis, data visualization and optimization. I like sports, crochet and piano.",
    statistics: 3,
    programming: 3,
    ux: 3,
  },
  {
    alias: "Flower",
    major: "interactive media technology",
    hobbies:
      "I like the art and technology. I am interested in learning new knowledge, painting, traveling, watching movies, reading books, and hiking.",
    statistics: 3,
    programming: 5,
    ux: 10,
  },
  {
    alias: "kapybara",
    major: "Computer Science",
    hobbies:
      "I like web design and want to work in front end development. In my spare time I enjoy different sports and spending time with my partner and dog.",
    statistics: 3,
    programming: 7,
    ux: 6,
  },
  {
    alias: "Bebocchia",
    major: "Media Technology",
    hobbies: "Part of a choir",
    statistics: 6,
    programming: 5,
    ux: 5,
  },
  {
    alias: "stellarise",
    major: "Computer Science",
    hobbies: "games especially , sports , animation, technology ",
    statistics: 6,
    programming: 8,
    ux: 5,
  },
  {
    alias: "Kakka",
    major: "Computer Science",
    hobbies: "",
    statistics: 3,
    programming: 8,
    ux: 4,
  },
  {
    alias: "Beowulf",
    major: "Media Technology",
    hobbies:
      "I enjoy creative programming, electronic art and gaming. Movies and cooking.",
    statistics: 3,
    programming: 8,
    ux: 6,
  },
  {
    alias: "BirdMaster",
    major: "Media Technology",
    hobbies: "theatre, exercise, reading, games, student activities ",
    statistics: 6,
    programming: 6,
    ux: 7,
  },
  {
    alias: "SargeSmoke",
    major: "Computer Science, Business Administration",
    hobbies:
      "Interest: Artificial Intelligence, Finance, Arts, Software Development. Hobbies: Sports (Volleyball, Badminton etc.), Gym, Video Games, Reading",
    statistics: 5,
    programming: 6,
    ux: 3,
  },
  {
    alias: "Weissach",
    major: "Engineering and Business Administration",
    hobbies:
      "I'm 24 years old from Germany. Manly I'm into cars, especially Porsche. Study wise there's machine learning and vehicle engineering. In my leisure time I love to play handball and watch Formula 1. ",
    statistics: 3,
    programming: 4,
    ux: 1,
  },
  {
    alias: "Croco",
    major: " mechanical engineering",
    hobbies: "Web Development",
    statistics: 6,
    programming: 2,
    ux: 2,
  },
  {
    alias: "w",
    major: "Data Science and Technology",
    hobbies: "I enjoy badminton and food",
    statistics: 6,
    programming: 6,
    ux: 3,
  },
  {
    alias: "kattmat",
    major: "Media Technology",
    hobbies: "politics, carpentry, bread making and, reading and riksgropen",
    statistics: 3,
    programming: 5,
    ux: 8,
  },
  {
    alias: "tofu",
    major: "Media Technology",
    hobbies: "Painting, knitting, crocheting, web development",
    statistics: 2,
    programming: 7,
    ux: 8,
  },
  {
    alias: "gallopinto",
    major: "Machine Learning",
    hobbies:
      "I am from Nicaragua but lived a bit all over the place since being a teenager. I am interested in how to use AI/ML for sustainable development -- specifically how to help improve living conditions in Nicaragua. This is one of the main reasons why I decided to do a BSc in Data Science and AI, and why I am now doing a MSc now Machine Learning. My current interests are to learn as much as I can and find ways how to achieve my long term goal, while meeting interesting people like-minded.",
    statistics: 5,
    programming: 5,
    ux: 4,
  },
  {
    alias: "numpy",
    major: "Machine Learning",
    hobbies: "Coding, machine learning, rock climbing",
    statistics: 9,
    programming: 7,
    ux: 2,
  },
  {
    alias: "Kanelbulle",
    major: "Computer Science",
    hobbies:
      "I enjoy storytelling of many sorts - writing, art, etc. I especially enjoy videogames, mainly games where you get to build your 'own thing'; like Cities: Skylines, Minecraft, the Sims, etc. I also really like factory-type games where you create your own flow of resources to build something greater.",
    statistics: 5,
    programming: 3,
    ux: 2,
  },
  {
    alias: "sackboy",
    major: "Computer Science",
    hobbies: "3D animation, programming, calisthenics, game development, art",
    statistics: 1,
    programming: 3,
    ux: 1,
  },
  {
    alias: "blackcat",
    major: "Medical engineering ",
    hobbies: "Like sports, nature and baking",
    statistics: 5,
    programming: 3,
    ux: 1,
  },
  {
    alias: "Shadowheart",
    major: "Media Technology",
    hobbies:
      "I like creating things and using design as a way of expression. On my free time, I also like playing video games.",
    statistics: 1,
    programming: 5,
    ux: 5,
  },
  {
    alias: "tpain",
    major: "Computer Science, Computer Science: Data Science",
    hobbies:
      "It is my first time abroad, and I am realizing travel is a major interest of mine. I chose to study computer science because I wanted to be a game developer, this is still my main interest almost a decade later. I am also very passionate about creating accessible computer science education for students from underprivileged backgrounds (such as myself) and have dedicated a lot of time at my home university working with such students. ",
    statistics: 5,
    programming: 6,
    ux: 2,
  },
  {
    alias: "ghostcat",
    major: "Human-Computer Interaction",
    hobbies: "Camera, Headphone, Computer Game, Cat",
    statistics: 5,
    programming: 8,
    ux: 5,
  },
  {
    alias: "cyan",
    major: "Real Estate",
    hobbies: "I love travelling, going to the gym and bowling.",
    statistics: 8,
    programming: 4,
    ux: 3,
  },
  {
    alias: "BlenderBender",
    major: "Media Technology",
    hobbies: "Blender, 3D printing, growing",
    statistics: 2,
    programming: 8,
    ux: 5,
  },
  {
    alias: "Windy65",
    major: "Electric Engineering",
    hobbies: "Fullfilling a big task interests me. I like playing instruments",
    statistics: 8,
    programming: 4,
    ux: 6,
  },
  {
    alias: "Bond, Jan Bond",
    major: "Computer Science",
    hobbies:
      "My biggest interests are related to technology, mostly math and problem solving related. I grew up painting a lot which have made me intersted in 3D art/modelling, but also procedural generation, texture generation and things like that. Other interstests is music, i play in keyboard in a pop band, and also movies and right now i play a lot of table tennis.",
    statistics: 3,
    programming: 5,
    ux: 2,
  },
  {
    alias: "MGH552200",
    major: "Media Technology",
    hobbies:
      "I like music, including music deep listening, playing and production. ",
    statistics: 5,
    programming: 8,
    ux: 4,
  },
  {
    alias: "John Wick",
    major: "Media Technology",
    hobbies:
      "My professional interests focus on machine learning and data science. My current skills for the future course project would be data preprocessing and data mining. Therefore, I hope to gain more skills on the visualization part. I like movies and video games as well.",
    statistics: 3,
    programming: 5,
    ux: 3,
  },
  {
    alias: "YellowShyGuy",
    major: "Computer Science",
    hobbies: "Sports like skiing, cycling, running",
    statistics: 7,
    programming: 8,
    ux: 4,
  },
  {
    alias: "Sam Vimes",
    major: "Computer Science",
    hobbies: "Reading",
    statistics: 3,
    programming: 3,
    ux: 2,
  },
  {
    alias: "Frieren",
    major: "Computer Science",
    hobbies:
      "I love cooking, photography, music, hiking/scouting and traveling. In particular Indian and Japanese cooking and listening to vinyls.",
    statistics: 6,
    programming: 7,
    ux: 6,
  },
  {
    alias: "DiscoTechLola",
    major: "Media Technology",
    hobbies: "I love dancing, storytelling and eating good food.",
    statistics: 2,
    programming: 3,
    ux: 4,
  },
  {
    alias: "Aaron",
    major: "Human-Computer Interaction",
    hobbies:
      "I'm a book nerd (including manga), cinephile, and music nerd (mainly rock n roll and specifically j-rock). I play football and skateboard.",
    statistics: 6,
    programming: 6,
    ux: 7,
  },
  {
    alias: "GGer",
    major: "Media Technology",
    hobbies: "I'm interested in ",
    statistics: 9,
    programming: 6,
    ux: 5,
  },
  {
    alias: "Reisen",
    major: "Vehicle Engineering",
    hobbies: "painting, playing guitar",
    statistics: 5,
    programming: 5,
    ux: 2,
  },
  {
    alias: "DrPavel",
    major: "Computer Science",
    hobbies:
      "Reading, video games, socializing, working out, It's a mixed blend.",
    statistics: 4,
    programming: 6,
    ux: 5,
  },
  {
    alias: "SannyKuro",
    major: "Media Technology",
    hobbies:
      "Creative technologist, crafty, Video editor, film making, storytelling, visual effects, accessibility — these are few words that can describe the kind of work I do. Out of which accessibility is also included as I would like to work towards making information visualised into digestable bits even for the non-technical mass. ",
    statistics: 5,
    programming: 8,
    ux: 7,
  },
  {
    alias: "Mintchoco",
    major: "Media Technology",
    hobbies:
      "Gym workouts, dance, technology, reading, travelling, TV/Movies, games",
    statistics: 6,
    programming: 7,
    ux: 7,
  },
];
